// <auto-generated />
using System;
using KolosProprawkowynr2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KolosProprawkowynr2.Migrations
{
    [DbContext(typeof(ArtistDbContext))]
    [Migration("20200625081236_InitialCreate1")]
    partial class InitialCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.5.20278.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KolosProprawkowynr2.Models.Artist", b =>
                {
                    b.Property<int?>("IDArtist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IDArtist");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            IDArtist = 1,
                            NickName = "DiStefano"
                        },
                        new
                        {
                            IDArtist = 2,
                            NickName = "DandaPerszo"
                        },
                        new
                        {
                            IDArtist = 3,
                            NickName = "BananaWhite"
                        });
                });

            modelBuilder.Entity("KolosProprawkowynr2.Models.Artist_Event", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtistIDArtist")
                        .HasColumnType("int");

                    b.Property<int?>("EventIdEvent")
                        .HasColumnType("int");

                    b.Property<int?>("IdArtist")
                        .HasColumnType("int");

                    b.Property<int?>("IdEvent")
                        .HasColumnType("int");

                    b.Property<DateTime>("PerformanceDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("ArtistIDArtist");

                    b.HasIndex("EventIdEvent");

                    b.ToTable("Artist_Event");
                });

            modelBuilder.Entity("KolosProprawkowynr2.Models.Event", b =>
                {
                    b.Property<int?>("IdEvent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEvent");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            IdEvent = 1,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DiscoPoloWLesie",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 2,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RapDlaPrzedszkolaków",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdEvent = 3,
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "RockAndRollWKlubieSeniora",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("KolosProprawkowynr2.Models.Organizer", b =>
                {
                    b.Property<int?>("IdOrganiser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("IdOrganiser");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            IdOrganiser = 1,
                            Name = "LasyPaństwowe"
                        },
                        new
                        {
                            IdOrganiser = 2,
                            Name = "Przedszkole nr 3"
                        },
                        new
                        {
                            IdOrganiser = 3,
                            Name = "Klub Seniora"
                        });
                });

            modelBuilder.Entity("KolosProprawkowynr2.Models.Artist_Event", b =>
                {
                    b.HasOne("KolosProprawkowynr2.Models.Artist", "Artist")
                        .WithMany("Events")
                        .HasForeignKey("ArtistIDArtist");

                    b.HasOne("KolosProprawkowynr2.Models.Event", "Event")
                        .WithMany("Artists")
                        .HasForeignKey("EventIdEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
